# .travis.yml
#
# To debug travis locally:
# https://docs.travis-ci.com/user/common-build-problems/#Running-a-Container-Based-Docker-Image-Locally
---
sudo: false
language: ruby
services:
  - docker
cache: bundler
before_install:
  - bundle install
  - bundle exec pdqtest setup
script: "make"
rvm:
  - 2.5.1
