image: ruby:2.3.5

pipelines:
  default:
    - step:
        caches:
          - bundler
        script:
          - ruby --version
          - bundler --version
          - bundle install
          - make logical

definitions:
  caches:
    bundler: vendor/bundle
